/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import javax.swing.*;
/*import javax.swing.JFrame;
import javax.swing.JTextField;
import javax.swing.JOptionPane;

import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;*/
import java.awt.Image;
import java.io.File;

/**
 *
 * @author Admin
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderOptions = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        FirstName = new javax.swing.JLabel();
        LastName = new javax.swing.JLabel();
        Age = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        Message = new javax.swing.JLabel();
        UploadPhoto = new javax.swing.JLabel();
        firstNameText = new javax.swing.JTextField();
        lastNameText = new javax.swing.JTextField();
        emailText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        messageText = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        uploadFile = new javax.swing.JButton();
        maleSelect = new javax.swing.JRadioButton();
        femaleSelect = new javax.swing.JRadioButton();
        otherSelect = new javax.swing.JRadioButton();
        Message1 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        howDidYouKnowAboutUs = new javax.swing.JLabel();
        knowAboutSelect = new javax.swing.JComboBox<>();
        previewImage = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        FirstName1 = new javax.swing.JLabel();
        LastName1 = new javax.swing.JLabel();
        Age1 = new javax.swing.JLabel();
        Email1 = new javax.swing.JLabel();
        Message2 = new javax.swing.JLabel();
        UploadPhoto1 = new javax.swing.JLabel();
        firstNameText1 = new javax.swing.JTextField();
        lastNameText1 = new javax.swing.JTextField();
        emailText1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        messageText1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        uploadFile1 = new javax.swing.JButton();
        maleSelect1 = new javax.swing.JRadioButton();
        femaleSelect1 = new javax.swing.JRadioButton();
        otherSelect1 = new javax.swing.JRadioButton();
        Message3 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(100, 500));
        setSize(new java.awt.Dimension(500, 500));

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setMinimumSize(new java.awt.Dimension(500, 500));

        jLabel2.setBackground(new java.awt.Color(0, 102, 102));
        jLabel2.setFont(new java.awt.Font("Stencil", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Customer Registration Form");

        FirstName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        FirstName.setText("First Name");

        LastName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LastName.setText("Last Name");

        Age.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Age.setText("Age");

        Email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Email.setText("Email");

        Message.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Message.setText("Message");

        UploadPhoto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        UploadPhoto.setText("Upload Photo (optional)");

        emailText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextActionPerformed(evt);
            }
        });

        messageText.setColumns(20);
        messageText.setLineWrap(true);
        messageText.setRows(5);
        messageText.setCaretColor(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(messageText);

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        uploadFile.setBackground(new java.awt.Color(0, 204, 204));
        uploadFile.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        uploadFile.setForeground(new java.awt.Color(255, 255, 255));
        uploadFile.setText("Choose a file...");
        uploadFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadFileActionPerformed(evt);
            }
        });

        genderOptions.add(maleSelect);
        maleSelect.setText("Male");
        maleSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleSelectActionPerformed(evt);
            }
        });

        genderOptions.add(femaleSelect);
        femaleSelect.setText("Female");
        femaleSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleSelectActionPerformed(evt);
            }
        });

        genderOptions.add(otherSelect);
        otherSelect.setSelected(true);
        otherSelect.setText("Other");
        otherSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherSelectActionPerformed(evt);
            }
        });

        Message1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Message1.setText("Gender");

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));

        howDidYouKnowAboutUs.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        howDidYouKnowAboutUs.setText("How did you know about us ? ");

        knowAboutSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one...", "Google", "Newspaper", "Through a friend", "None of the Above" }));

        previewImage.setBackground(new java.awt.Color(204, 255, 204));
        previewImage.setMaximumSize(new java.awt.Dimension(150, 150));
        previewImage.setMinimumSize(new java.awt.Dimension(150, 150));
        previewImage.setOpaque(true);
        previewImage.setPreferredSize(new java.awt.Dimension(150, 150));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(firstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(maleSelect)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(knowAboutSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(uploadFile, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(UploadPhoto)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Age)
                            .addComponent(LastName)
                            .addComponent(Email)
                            .addComponent(Message)
                            .addComponent(Message1)
                            .addComponent(howDidYouKnowAboutUs)
                            .addComponent(FirstName))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(femaleSelect)
                                .addGap(18, 18, 18)
                                .addComponent(otherSelect))
                            .addComponent(previewImage, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(71, 71, 71))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addGap(5, 5, 5)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstName)
                    .addComponent(firstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(LastName))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Age)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(Email))
                    .addComponent(emailText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Message1)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(maleSelect)
                        .addComponent(femaleSelect)
                        .addComponent(otherSelect)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(howDidYouKnowAboutUs)
                    .addComponent(knowAboutSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Message)
                        .addGap(40, 40, 40))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UploadPhoto)
                    .addComponent(uploadFile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(previewImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setMinimumSize(new java.awt.Dimension(500, 500));

        jLabel3.setBackground(new java.awt.Color(0, 102, 102));
        jLabel3.setFont(new java.awt.Font("Stencil", 1, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Customer Registration Form");

        FirstName1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        FirstName1.setText("First Name");

        LastName1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LastName1.setText("Last Name");

        Age1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Age1.setText("Age");

        Email1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Email1.setText("Email");

        Message2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Message2.setText("Message");

        UploadPhoto1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        UploadPhoto1.setText("Upload Photo");

        emailText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailText1ActionPerformed(evt);
            }
        });

        messageText1.setColumns(20);
        messageText1.setLineWrap(true);
        messageText1.setRows(5);
        messageText1.setCaretColor(new java.awt.Color(204, 204, 204));
        jScrollPane2.setViewportView(messageText1);

        jButton2.setBackground(new java.awt.Color(0, 204, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        uploadFile1.setBackground(new java.awt.Color(0, 204, 204));
        uploadFile1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        uploadFile1.setForeground(new java.awt.Color(255, 255, 255));
        uploadFile1.setText("Choose a file...");
        uploadFile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadFile1ActionPerformed(evt);
            }
        });

        genderOptions.add(maleSelect1);
        maleSelect1.setText("Male");
        maleSelect1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleSelect1ActionPerformed(evt);
            }
        });

        genderOptions.add(femaleSelect1);
        femaleSelect1.setText("Female");
        femaleSelect1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleSelect1ActionPerformed(evt);
            }
        });

        genderOptions.add(otherSelect1);
        otherSelect1.setText("Other");
        otherSelect1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherSelect1ActionPerformed(evt);
            }
        });

        Message3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Message3.setText("Gender");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(FirstName1)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Age1)
                                    .addComponent(LastName1)
                                    .addComponent(Email1)
                                    .addComponent(Message2)
                                    .addComponent(Message3)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(UploadPhoto1)))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(emailText1)
                                .addComponent(lastNameText1)
                                .addComponent(firstNameText1)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(uploadFile1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(maleSelect1)
                                .addGap(18, 18, 18)
                                .addComponent(femaleSelect1)
                                .addGap(18, 18, 18)
                                .addComponent(otherSelect1))
                            .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstName1)
                    .addComponent(firstNameText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LastName1)
                    .addComponent(lastNameText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Age1)
                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Email1)
                    .addComponent(emailText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maleSelect1)
                    .addComponent(femaleSelect1)
                    .addComponent(otherSelect1)
                    .addComponent(Message3))
                .addGap(114, 114, 114)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Message2))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uploadFile1)
                    .addComponent(UploadPhoto1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2574, 2574, 2574)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailText1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void uploadFile1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadFile1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uploadFile1ActionPerformed

    private void maleSelect1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleSelect1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleSelect1ActionPerformed

    private void femaleSelect1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleSelect1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleSelect1ActionPerformed

    private void otherSelect1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherSelect1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_otherSelect1ActionPerformed

    private void otherSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_otherSelectActionPerformed

    private void femaleSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleSelectActionPerformed

    private void maleSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleSelectActionPerformed

    private void uploadFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadFileActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        int returnValue = fileChooser.showOpenDialog(null);

        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            if (selectedFile.getName().endsWith(".jpg") || selectedFile.getName().endsWith(".png")) {
                ImageIcon imageIcon = new ImageIcon(selectedFile.getPath());
                Image image = imageIcon.getImage().getScaledInstance(150, 150, Image.SCALE_SMOOTH);
                previewImage.setIcon(new ImageIcon(image));
            } else {
                JOptionPane.showMessageDialog(null, "Please select a image! ", "Invalid Input", JOptionPane.ERROR_MESSAGE);
        
            }
        }
        
    }//GEN-LAST:event_uploadFileActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        validateAllField();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void emailTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextActionPerformed
    
    
    private void validateAllField(){
        String firstName = firstNameText.getText();
        String lastName = lastNameText.getText();
        int age = (int)jSpinner1.getValue();
        String email = emailText.getText();
        String message = messageText.getText();
        String gender = genderOptions.getSelection().getActionCommand();
        
        
        if(firstName.length()<1 || firstName.length()>26 || !firstName.matches("^[a-zA-Z]+")){
                JOptionPane.showMessageDialog(null, "Please enter a First Name with: \n1. Length between 1 and 20 characters. \n2. Chararcters from A...Z or a..z.\n3. No special characters. ", "Invalid Input", JOptionPane.ERROR_MESSAGE);
        }
        else{
           
                if(lastName.length()<1 || lastName.length()>26){
                    JOptionPane.showMessageDialog(null, "Please enter a First Name with: \n1. Length between 1 and 20 characters. \n2. Chararcters from A...Z or a..z. \n3. No special characters. ", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                }else{
                    if(!lastName.matches("^[a-zA-Z]+")){
                            JOptionPane.showMessageDialog(null, "Please enter a Last Name with chararcters from A...Z or a..z.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                    }else{
                         if(age<12 || age>101){
                                JOptionPane.showMessageDialog(null, "Please enter age between 12 and 100 (both inclusive).", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                           }
                           else{
                                if(!email.matches("[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$")){
                                    JOptionPane.showMessageDialog(null, "Please enter valid email address.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                       
                                }
                                else{
                                    if(!maleSelect.isSelected() && !femaleSelect.isSelected() && !otherSelect.isSelected()){
                                        JOptionPane.showMessageDialog(null, "Please select any one of the Gender options!", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                                    }
                                    else{
                                        if (knowAboutSelect.getSelectedIndex() == -1) {
                                            JOptionPane.showMessageDialog(null, "Please select any one of the Gender options!", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                                    
                                        }
                                        else{
                                            if(message.length()<1){
                                                JOptionPane.showMessageDialog(null, "Please enter a message for our team!", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                                            }else{
                                                JOptionPane.showMessageDialog(null, "Your information has been successfully recorded. Below are the details that are submitted.\nFirst Name: "+firstName+"\nLast Name: "+lastName+"\nAge: "+age+"\nGender: "+gender+"\nHow did you find out about us?: "+knowAboutSelect.getSelectedItem()+"\nMessage: "+message, "Registration Successful!!!", JOptionPane.INFORMATION_MESSAGE);
                                            }
                                             }
                                        
                                        
                                    }
                                }
                                
                            }
                            
                    }
                }
          
        }                              
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Age;
    private javax.swing.JLabel Age1;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Email1;
    private javax.swing.JLabel FirstName;
    private javax.swing.JLabel FirstName1;
    private javax.swing.JLabel LastName;
    private javax.swing.JLabel LastName1;
    private javax.swing.JLabel Message;
    private javax.swing.JLabel Message1;
    private javax.swing.JLabel Message2;
    private javax.swing.JLabel Message3;
    private javax.swing.JLabel UploadPhoto;
    private javax.swing.JLabel UploadPhoto1;
    private javax.swing.JTextField emailText;
    private javax.swing.JTextField emailText1;
    private javax.swing.JRadioButton femaleSelect;
    private javax.swing.JRadioButton femaleSelect1;
    private javax.swing.JTextField firstNameText;
    private javax.swing.JTextField firstNameText1;
    private javax.swing.ButtonGroup genderOptions;
    private javax.swing.JLabel howDidYouKnowAboutUs;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JComboBox<String> knowAboutSelect;
    private javax.swing.JTextField lastNameText;
    private javax.swing.JTextField lastNameText1;
    private javax.swing.JRadioButton maleSelect;
    private javax.swing.JRadioButton maleSelect1;
    private javax.swing.JTextArea messageText;
    private javax.swing.JTextArea messageText1;
    private javax.swing.JRadioButton otherSelect;
    private javax.swing.JRadioButton otherSelect1;
    private javax.swing.JLabel previewImage;
    private javax.swing.JButton uploadFile;
    private javax.swing.JButton uploadFile1;
    // End of variables declaration//GEN-END:variables
private JLabel photoPreviewLabel;
}
